# Define a imagem base
FROM node:14.18.3-alpine3.15

# Define o diretório de trabalho
WORKDIR /app

# Copia o arquivo package.json para o diretório de trabalho
COPY ./front/package.json .

# Instala as dependências do projeto
RUN npm install

# Copia todo o código do frontend para o diretório de trabalho
COPY ./front .

# Expõe a porta 3000
EXPOSE 3000

# Inicia o servidor do frontend
CMD ["npm", "start"]


# rodar da pasta raiz -> docker build -t timeline_frontend -f Dockerfile_frontend .
