FROM php:8.2-fpm

RUN apt update && docker-php-ext-install pdo_mysql

RUN apt install -y git && apt install -y zip

RUN curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
RUN php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer

COPY ./api/docker-entrypoint.sh /

RUN chmod +x /docker-entrypoint.sh

WORKDIR /www

COPY ./api .

RUN composer install && chmod 777 -R storage/

EXPOSE 80

## Add the wait script to the image
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.10.0/wait /wait
RUN chmod +x /wait

RUN /docker-entrypoint.sh

# rodar da pasta raiz -> docker build -t timeline_api -f Dockerfile_api .