version: '3.8'

services:
  frontend:
    image: timeline_frontend
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    networks:
      timeline:
        ipv4_address: 172.20.0.3
    depends_on:
      - api
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=front.timeline.com

  # api:
  #   image: timeline_api
  #   build: ./api
  #   ports:
  #     - "9000:9000"
  #   networks:
  #     timeline:
  #       ipv4_address: 172.20.0.4
  #   depends_on:
  #     - mysql
  #   env_file:
  #     - .env
  #   environment:
  #     - VIRTUAL_HOST=api.timeline.com
  #     - VIRTUAL_PORT=9000
  #   volumes:
  #     - ./api:/var/www/html

  api:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=api.timeline.com
      # - VIRTUAL_PORT=9000
    networks:
      timeline:
        ipv4_address: 172.20.0.4
    volumes:
      - ./api:/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    depends_on:
      - php
    volumes_from:
      - php

  php:
    image: php:8.2-fpm
    container_name: php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./api:/www
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    networks:
      timeline:
        ipv4_address: 172.20.0.5
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=mysql.timeline.com
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      interval: 10s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: php-myadmin
    hostname: tlb
    restart: always
    ports:
      - '127.0.0.1:8080:80'
    networks:
      timeline:
        ipv4_address: 172.20.0.6
    environment:
      - PMA_ARBITRARY=1
      - VIRTUAL_HOST=pma.timeline.com
    links:
      - mysql

  # nginx-proxy:
  #   image: jwilder/nginx-proxy
  #   ports:
  #     - "80:80"
  #     - "3000:3000"
  #     - "3306:3306"
  #     - "9000:9000"
  #   networks:
  #     timeline:
  #       ipv4_address: 172.20.0.2
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  mysql_data:

networks:
  timeline:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

