# Define a imagem base
FROM php:8.2-apache

# Habilita o módulo de reescrita do Apache
RUN a2enmod rewrite

# Instala as dependências necessárias
RUN apt-get update && \
    apt-get install -y \
        libicu-dev \
        libpq-dev \
        zip \
        unzip && \
    docker-php-ext-install \
        intl \
        pdo_mysql && \
    pecl install \
        xdebug && \
    docker-php-ext-enable \
        xdebug

# Instala o Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Define o diretório de trabalho
WORKDIR /var/www/html

# Copia todo o código do backend para o diretório de trabalho
COPY ./api .

# Instala as dependências do Laravel
RUN composer install --no-dev

# Define as variáveis de ambiente necessárias
ENV DB_HOST localhost
ENV DB_PORT 3306
ENV DB_DATABASE timelinebuilder
ENV DB_USERNAME root
ENV DB_PASSWORD password

# Gera uma nova chave de aplicação para o Laravel
RUN php artisan key:generate

# Expõe a porta 8000
EXPOSE 8000

# Inicia o servidor do Apache
CMD ["apache2-foreground"]
